apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  generation: 1
  labels:
    run: next-demo
  name: next-demo
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/next-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      run: next-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: next-demo
    spec:
      containers:
      - command:
        - node
        - app/server.js
        image: gcr.io/wdenniss-gke-next17/bitbucket-wdenniss
        imagePullPolicy: IfNotPresent
        name: next-demo
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
